name: Try kernel build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Installing Dependencies and Enviroment
        run: |
          sudo apt install -y python3 python3-pip build-essential
          python -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt

      - name: Release Build
        run: |
          source venv/bin/activate
          exec ./tools/get-kernel-build.sh